#!/usr/bin/env perl

#   Copyright 2015 Darius Kellermann
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Recurses over linked LaTeX source files and creates dependency information for
# use with GNU make.
#
# Call with the main LaTeX source file as the sole argument:
#
#     latexdeps <main source file>

use strict;
use warnings;

sub parse_tex {
	my $texf = shift;
	my $wd = shift;
	my @deps;

	$texf = "$wd$texf" unless not defined $wd;

	open(my $texin, "<", "$texf") or die "latexdeps: $texf: $!";

	while (<$texin>) {
		if (/\\include\{([^\}]*)\}/) {
			next if "$1.tex" ~~ @deps;
			push(@deps, parse_tex("$1.tex", $wd), "$1.tex");
		}
		elsif (/\\import(\{([^\}]*)\})?\{([^\}]*)\}/) {
			next if "$2$3" ~~ @deps;
			push(@deps, "$2$3");
		}
		elsif (/\\lstinputlisting(\[[^\]]*\])?\{([^\}]*)\}/) {
			next if "$2" ~~ @deps;
			push(@deps, "$2");
		}
	}

	return @deps;
}

my $texf = $ARGV[0];
my $bn;
my $wd;
my $base;

if ($texf =~ /((.*)\/)?(([^\/]+).tex)$/) {
	$wd = $1;
	$bn = $3;
	$base = $4;
}
else {
	die "latexdeps: $texf: not a valid tex filename";
}

my @deps = ("$base.tex");
push(@deps,parse_tex($bn, $wd));

print "$base.pdf $base.d: @deps $base.aux\n";

exit 0;
